modLoader="javafml"
loaderVersion="[38,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/EnhancedPixel/Configured/issues"
[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="EnhancedPixel Team"
    description="Simple configuration library made for Minecraft modders."