name: Java workflows using Gradle

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.txt'
      - 'README.md'
      - 'LICENSE'
      - 'LICENSE.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.txt'
      - 'README.md'
      - 'LICENSE'
      - 'LICENSE.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  build:
    name: "Attempt Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --no-daemon --stacktrace

      - name: Cache
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*.jar